### PR TITLE
fix: https.get would make a http request

### LINKED ISSUE #6: https.get doesn't use https.request
`https.get` doesn't use overloaded `https.request`. Instead it uses `http.request`.
This is caused by the fact that `http.get` uses directly `http.request`: https://github.com/substack/http-browserify/blob/master/index.js#L44 and don't know anything about overloaded version.
Need to overload `https.get` method as well.

### PR DESCRIPTION
**Pull request by RomanGotsiy**
closes #6

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -12,3 +12,9 @@ https.request = function (params, cb) {
     params.protocol = 'https:';
     return http.request.call(this, params, cb);
 }
+
+https.get = function (params, cb) {
+    if !(params) params = {}
```
Comment (feross) [inline index.js]: Is this valid syntax? Did you mean this instead:

```js
if (!params) params = {}
```

File: index.js [hunk 2]
```diff
@@ -12,3 +12,9 @@ https.request = function (params, cb) {
...
+    params.protocol = 'https:';
```
Comment (feross) [inline index.js]: `https.get` can also accept a string as the first argument, like this:

```js
https.get('https://encrypted.google.com/', (res) => {
  ...
}
```

Can you also make sure to handle this case?

**Comment by feross** [comment]
cc @jhiesey who is interested in this too

File: index.js (hunk 1 above)
Comment (RomanGotsiy) [inline index.js]: 😱 @feross yes. Thanks, fixed.

File: index.js (hunk 2 above)
Comment (RomanGotsiy) [inline index.js]: @feross How do you want to handle this? What to do when user tries to get `http` page using `https` module, e.g.:

```js
https.get('http://encrypted.google.com/', (res) => {
  ...
}
```
There are two variants:
1) just ignore, then this call will be passed to `stream-http` and it will get page using `http`
2) parse URL before passing it to `stream-http` and set `protocol` to `https:`

What do you prefer?

Comment (feross) [inline index.js]: It looks like Node.js throws an error: `Error: Protocol "http:" not supported. Expected "https:"`. Let's do the same. The objective of these browser shim packages is to match Node.js behavior as closely as possible.

**Comment by feross** [comment]
Published as 1.0.0.
